# Generated by Django 3.0 on 2021-09-18 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_auto_20210918_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='model_number',
            field=models.CharField(default=uuid.uuid4, help_text='This is used to identify this model', max_length=36, unique=True, verbose_name='Model Number'),
        ),
    ]
