# Generated by Django 3.0 on 2021-09-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceLabels',
            new_name='InvoiceLabel',
        ),
    ]
